name: MOM
description: "Task tracking for everyone, by everyone. It's just a matter of moments."
meta_description: "Task tracking for everyone, by everyone. It's just a matter of moments."

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'blog url'
author:         'Your Name'
