name: MOM
description: "Keeping track of ourselves is a matter of moments."
meta_description: "Keeping track of ourselves is a matter of moments."

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'blog url'
author:         'Your Name'
